---
version: 2
updates:
- package-ecosystem: "maven"
  open-pull-requests-limit: 20
  directory: "/"
  schedule:
    interval: "weekly"
    day: "monday"
    time: "06:00"
    timezone: "Europe/Stockholm"
  labels:
    - "Technical Debt"
    - "dependencies"
